const express = require('express');
const { requireAuth, optionalAuth } = require('../middleware/auth');
const { verifyWallet } = require('../services/wallet');
const { scanInventory } = require('../services/inventory');
const { matchEpisode } = require('../services/matching');
const { episodes, analytics, inventoryCache } = require('../db');
const router = express.Router();
router.get('/health', function(req, res) { res.json({ status: 'ok', version: '1.0.0', uptime: Math.floor(process.uptime()) }); });
router.post('/verify-wallet', async function(req, res, next) { try { var b = req.body; if (!b.address || !b.message || !b.signature) return res.status(400).json({ error: 'Missing fields' }); res.json(await verifyWallet(b.address, b.message, b.signature)); } catch (err) { next(err); } });
router.get('/inventory/:address', async function(req, res, next) { try { if (!/^0x[0-9a-fA-F]{40}$/.test(req.params.address)) return res.status(400).json({ error: 'Invalid address' }); res.json(await scanInventory(req.params.address)); } catch (err) { next(err); } });
router.get('/match/:address/:episodeId', async function(req, res, next) { try { if (!/^0x[0-9a-fA-F]{40}$/.test(req.params.address)) return res.status(400).json({ error: 'Invalid address' }); res.json(await matchEpisode(req.params.address, req.params.episodeId)); } catch (err) { next(err); } });
router.get('/episodes', function(req, res) { res.json({ episodes: episodes.getAll.all() }); });
router.get('/episodes/:id', function(req, res) { var row = episodes.getById.get(req.params.id); if (!row) return res.status(404).json({ error: 'Not found' }); var info = Object.assign({}, row); delete info.manifest; res.json(info); });
router.get('/manifest/:episodeId', function(req, res) { var row = episodes.getById.get(req.params.episodeId); if (!row) return res.status(404).json({ error: 'Not found' }); try { res.json(JSON.parse(row.manifest)); } catch (e) { res.status(500).json({ error: 'Bad manifest' }); } });
router.post('/analytics/event', optionalAuth, function(req, res) { try { var b = req.body; if (!b.event_type) return res.status(400).json({ error: 'Missing event_type' }); analytics.track.run(b.event_type, req.walletAddress || null, b.episode_id || null, b.slot_id || null, b.nft_token_id || null, b.metadata ? JSON.stringify(b.metadata) : null); res.json({ tracked: true }); } catch (err) { res.json({ tracked: false }); } });
router.get('/clear-cache', function(req, res) { inventoryCache.invalidate(req.query.address || ''); res.json({ cleared: true }); });
module.exports = router;
